name: cavoke # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0-beta' # just for humans, typically '1.2+git' or '1.3.2'
summary:  The network game Cavoke
description: |
   The network game Cavoke

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  cavoke_icon.png
title: Cavoke

apps:
  cavoke:
    command: cavoke
parts:
  cavoke:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      cavoke: build/
      cavoke.1: man/man1/

architectures:
  - build-on: amd64

